---
- name: Add sandbox hosts entry
  ansible.builtin.lineinfile:
    path: "{{ sandboxing_hosts_file }}"
    create: true
    owner: root
    group: root
    mode: "0644"
    regexp: >
      ^\s*[^#]*\s+{{ sandboxing_name }}\s*(#.*)?$
    line: "{{ sandboxing_network_base_octets }}.{{ sandboxing_vm_ip_octet }} {{ sandboxing_name }}"
    # bind-mounts do not support atomic writes
    unsafe_writes: "{{
      ansible_facts['virtualization_type'] is defined and
      ansible_facts['virtualization_type'] in ['docker', 'containerd', 'container', 'podman', 'lxc', 'lxd']
      }}"
  vars:
    sandboxing_vm_ip_octet: "{{ (sandboxing_index | int * sandboxing_network_size) + 2 }}"

- name: Add sandbox gateway hosts entry
  ansible.builtin.lineinfile:
    path: "{{ sandboxing_hosts_file }}"
    create: true
    owner: root
    group: root
    mode: "0644"
    regexp: >
      ^\s*[^#]*\s+gateway_{{ sandboxing_name }}\s*(#.*)?$
    line: "{{ sandboxing_network_base_octets }}.{{ sandboxing_gateway_ip_octet }} gateway_{{ sandboxing_name }}"
    # bind-mounts do not support atomic writes
    unsafe_writes: "{{
      ansible_facts['virtualization_type'] is defined and
      ansible_facts['virtualization_type'] in ['docker', 'containerd', 'container', 'podman', 'lxc', 'lxd']
      }}"
  vars:
    sandboxing_gateway_ip_octet: "{{ (sandboxing_index | int * sandboxing_network_size) + 1 }}"
