---
- name: Validate sandbox name
  ansible.builtin.assert:
    that:
      - sandboxing_name is regex(sandboxing_base_name_regex, match_type="fullmatch")
    fail_msg: "{{ sandboxing_name }} must match {{ sandboxing_base_name_regex }} regex"

- name: Setup user
  ansible.builtin.import_tasks:
    file: user.yml

- name: Setup network
  ansible.builtin.import_tasks:
    file: network.yml

- name: Setup hosts entry
  ansible.builtin.import_tasks:
    file: hosts.yml
