# firewalld config file

# https://manpages.debian.org/trixie/firewalld/firewalld.conf.5.en.html

DefaultZone=public

# CHANGED: cleaning up rules on exit means unprotected
CleanupOnExit=no

CleanupModulesOnExit=no

IPv6_rpfilter=strict

IndividualCalls=no

# enable for debugging only
LogDenied=off

FirewallBackend=nftables

FlushAllOnReload=yes

# this is inherited for default chain policies, when target=default
ReloadPolicy=INPUT:DROP,FORWARD:DROP,OUTPUT:DROP

RFC3964_IPv4=yes

# TODO: check if podman containers still work implicitely with 'yes'
StrictForwardPorts=no

NftablesFlowtable=off

# CHANGED: enabled for debugging, low impact
NftablesCounters=yes

NftablesTableOwner=yes
